"""empty message

Revision ID: 11d5e81c8bef
Revises: 2feddc821f7b
Create Date: 2026-09-23 18:46:23.810961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '11d5e81c8bef'
down_revision: Union[str, Sequence[str], None] = '2feddc821f7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('radar_candidatos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alerta_venta_enviada', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('radar_candidatos', schema=None) as batch_op:
        batch_op.drop_column('alerta_venta_enviada')

    # ### end Alembic commands ###
