"""empty message

Revision ID: 2feddc821f7b
Revises: 9acb4a6134f7
Create Date: 2026-09-23 18:06:02.217296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '2feddc821f7b'
down_revision: Union[str, Sequence[str], None] = '9acb4a6134f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('radar_candidatos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alerta_enviada', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('radar_candidatos', schema=None) as batch_op:
        batch_op.drop_column('alerta_enviada')

    # ### end Alembic commands ###
