"""empty message

Revision ID: 3059007439a2
Revises: a3592e3bfc1d
Create Date: 2026-09-24 13:37:48.939411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3059007439a2'
down_revision: Union[str, Sequence[str], None] = 'a3592e3bfc1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ejecuciones_radar_horarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ejecutada_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ejecuciones_radar_horarias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ejecuciones_radar_horarias_clave'), ['clave'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ejecuciones_radar_horarias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ejecuciones_radar_horarias_clave'))

    op.drop_table('ejecuciones_radar_horarias')
    # ### end Alembic commands ###
