"""tablas del modelo completo

Revision ID: 6fe6176eb178
Revises: 
Create Date: 2026-09-17 17:35:45.638442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6fe6176eb178'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brokers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('sectores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supersector', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sector', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grupo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supersector', 'sector', 'grupo', name='uq_sector_jerarquia')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    op.create_table('carteras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('tipo_cartera', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_usuario', 'tipo_cartera', name='uq_cartera_usuario_tipo')
    )
    op.create_table('valores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('empresa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_sector', sa.Integer(), nullable=False),
    sa.Column('zona', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cotizacion_divisa', sa.Float(), nullable=True),
    sa.Column('cotizacion_eur', sa.Float(), nullable=True),
    sa.Column('cotizacion_actualizada_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_sector'], ['sectores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('valores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_valores_ticker'), ['ticker'], unique=True)

    op.create_table('operaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cartera', sa.Integer(), nullable=False),
    sa.Column('id_valor', sa.Integer(), nullable=False),
    sa.Column('id_broker', sa.Integer(), nullable=False),
    sa.Column('tipo_operacion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('num_titulos', sa.Float(), nullable=False),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('importe_unitario', sa.Float(), nullable=True),
    sa.Column('retencion_origen', sa.Float(), nullable=True),
    sa.Column('retencion_destino', sa.Float(), nullable=True),
    sa.Column('tipo_derecho_script', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('observaciones', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['id_broker'], ['brokers.id'], ),
    sa.ForeignKeyConstraint(['id_cartera'], ['carteras.id'], ),
    sa.ForeignKeyConstraint(['id_valor'], ['valores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operaciones')
    with op.batch_alter_table('valores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_valores_ticker'))

    op.drop_table('valores')
    op.drop_table('carteras')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    op.drop_table('sectores')
    op.drop_table('brokers')
    # ### end Alembic commands ###
