"""moneda en valores

Revision ID: 728a02d53fa8
Revises: affe368cbebc
Create Date: 2026-09-17 19:02:27.876042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '728a02d53fa8'
down_revision: Union[str, Sequence[str], None] = 'affe368cbebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('valores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moneda', sqlmodel.sql.sqltypes.AutoString(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('valores', schema=None) as batch_op:
        batch_op.drop_column('moneda')

    # ### end Alembic commands ###
