"""empty message

Revision ID: 74a2399fa7e7
Revises: c4acce44f64f
Create Date: 2026-09-25 11:35:08.724069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '74a2399fa7e7'
down_revision: Union[str, Sequence[str], None] = 'c4acce44f64f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_valor_relacionado', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pct_reparto', sa.Float(), nullable=True))
        batch_op.create_foreign_key(
            'fk_operaciones_id_valor_relacionado_valores', 'valores', ['id_valor_relacionado'], ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operaciones', schema=None) as batch_op:
        batch_op.drop_constraint('fk_operaciones_id_valor_relacionado_valores', type_='foreignkey')
        batch_op.drop_column('pct_reparto')
        batch_op.drop_column('id_valor_relacionado')

    # ### end Alembic commands ###
