"""add radar_candidatos

Revision ID: 9acb4a6134f7
Revises: 2904ca3b4deb
Create Date: 2026-09-22 16:47:55.477370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9acb4a6134f7'
down_revision: Union[str, Sequence[str], None] = '2904ca3b4deb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radar_candidatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_valor', sa.Integer(), nullable=False),
    sa.Column('tipo_lista', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('importe_invertir', sa.Float(), nullable=False),
    sa.Column('precio_max', sa.Float(), nullable=False),
    sa.Column('precio_min', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_valor'], ['valores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_usuario', 'id_valor', 'tipo_lista', name='uq_radar_candidato_usuario_valor_lista')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('radar_candidatos')
    # ### end Alembic commands ###
