"""empty message

Revision ID: a3592e3bfc1d
Revises: e9ca85431fd7
Create Date: 2026-09-24 13:02:59.251806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3592e3bfc1d'
down_revision: Union[str, Sequence[str], None] = 'e9ca85431fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('radar_candidatos', schema=None) as batch_op:
        batch_op.alter_column('precio_max',
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('radar_candidatos', schema=None) as batch_op:
        batch_op.alter_column('precio_max',
               nullable=False)

    # ### end Alembic commands ###
