"""usuarios: password y activo

Revision ID: affe368cbebc
Revises: 6fe6176eb178
Create Date: 2026-09-17 18:19:58.070882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'affe368cbebc'
down_revision: Union[str, Sequence[str], None] = '6fe6176eb178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debe_cambiar_password', sa.Boolean(), server_default=sa.text('1'), nullable=False))
        batch_op.add_column(sa.Column('activo', sa.Boolean(), server_default=sa.text('1'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('activo')
        batch_op.drop_column('debe_cambiar_password')

    # ### end Alembic commands ###
