"""empty message

Revision ID: c4acce44f64f
Revises: 3059007439a2
Create Date: 2026-09-24 18:29:39.940660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c4acce44f64f'
down_revision: Union[str, Sequence[str], None] = '3059007439a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ratio', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tipo_ajuste_fraccion', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operaciones', schema=None) as batch_op:
        batch_op.drop_column('tipo_ajuste_fraccion')
        batch_op.drop_column('ratio')

    # ### end Alembic commands ###
