"""mercado en valores, unique ticker+mercado

Revision ID: cea999ed2487
Revises: 728a02d53fa8
Create Date: 2026-09-18 12:13:15.122664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'cea999ed2487'
down_revision: Union[str, Sequence[str], None] = '728a02d53fa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('valores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mercado', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_valores_ticker'))
        batch_op.create_index(batch_op.f('ix_valores_ticker'), ['ticker'], unique=False)
        batch_op.create_unique_constraint('uq_valor_ticker_mercado', ['ticker', 'mercado'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('valores', schema=None) as batch_op:
        batch_op.drop_constraint('uq_valor_ticker_mercado', type_='unique')
        batch_op.drop_index(batch_op.f('ix_valores_ticker'))
        batch_op.create_index(batch_op.f('ix_valores_ticker'), ['ticker'], unique=1)
        batch_op.drop_column('mercado')

    # ### end Alembic commands ###
