"""empty message

Revision ID: e9ca85431fd7
Revises: c03dedfc7da6
Create Date: 2026-09-24 12:34:45.087043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e9ca85431fd7'
down_revision: Union[str, Sequence[str], None] = 'c03dedfc7da6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono_avisos', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.drop_column('telefono_whatsapp')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono_whatsapp', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('telefono_avisos')

    # ### end Alembic commands ###
